name: nbcheck
description: Run checks on Jupyter notebooks
inputs:
  type:
    required: true
    description: Type of check to perform. Options are 'static', 'execution'.
  setup-python:
    required: false
    description: |
      Whether the action should set up its own Python environment,
      or use the one created by the job
    default: "false"
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v2
      if: inputs.setup-python
      with:
        python-version: '3.10'
    - name: Install Python package with dependencies
      shell: bash
      env:
        SETUPTOOLS_SCM_PRETEND_VERSION: ${{ github.action_ref }}
      working-directory: ${{ github.action_path }}
      run: |
        pip install --progress-bar off .
        pip show dispatches-nbcheck pytest nbformat nbval
    - name: Add common pytest options
      shell: bash
      run: |
        echo 'PYTEST_ADDOPTS=--color=yes' >> "$GITHUB_ENV"
    - name: Run static tests (i.e. without executing the notebooks)
      if: inputs.type == 'static'
      shell: bash
      env:
        NBCHECK_TEST_FILE: ${{ github.action_path }}/tests/test_static.py
      run: |
        pytest "$NBCHECK_TEST_FILE"
    - name: Run tests executing the notebooks
      if: inputs.type == 'execution'
      shell: bash
      run: |
        pytest --durations=20 --durations-min=1.0 --nbval-lax