name: nbcheck
description: Run checks on Jupyter notebooks
inputs:
  type:
    required: true
    description: Type of check to perform. Options are 'static', 'execution'.
  setup-python:
    required: false
    description: |
      Whether the action should set up its own Python environment,
      or use the one created by the job
    default: "false"
  pytest-extra-flags:
    required: false
    description: Extra flags to pass to the pytest call
    default: ""
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v2
      if: fromJSON(inputs.setup-python)
      with:
        python-version: '3.10'
    - name: Install Python package with dependencies
      env:
        _pip_install_target: git+https://github.com/${{ github.action_repository }}@${{ github.action_ref }}
      shell: bash
      run: |
        pip install --progress-bar off "$_pip_install_target"
        pip show dispatches-nbcheck pytest nbformat nbval
    - name: Add common pytest options
      shell: bash
      run: |
        echo 'PYTEST_ADDOPTS="--color=yes ${{ inputs.pytest-extra-flags }}"' >> "$GITHUB_ENV"
    - name: Run static tests (i.e. without executing the notebooks)
      if: inputs.type == 'static'
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        pytest "${{ github.action_path }}/static/"
    - name: Run tests executing the notebooks
      if: inputs.type == 'execution'
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        pytest -c "${{ github.action_path }}/execution/pytest.ini" --rootdir=. .
